auto: true
exclude:
- bootstrap
- README.md
- CssMinify.yml
- Gemfile
- Gemfile.lock
- incubation
- css # CssMinify will generate the CSS and place it under _site
- Rakefile
permalink: none
pygments: true
